service: simply-serverless-cron-job

provider:
  name: aws
  runtime: go1.x
  profile: simply-serverless

functions:
  cron-job:
    handler: bin/cron-job
    events:
      - schedule:
          rate: rate(1 minute)
      - schedule:
          rate: cron(0 17 * * ? *)

package:
  exclude:
    - ./**
  include:
    - ./bin/**